# -*- coding: ISO-8859-1 -*-
#
# Fichero:	ayuda.py
# Copyright:	Junta de Andalucía <devmaster@guadalinex.org>
# Autor:	Maria Dolores Perez Gutierrez y Nestor Chacon Manzano
# Fecha:	lun mar 27 17:01:23 CET 2006
# Licencia:	GPL v.2
#
# generated by wxGlade 0.3.5.1 on Tue Feb  7 17:05:09 2006
#
# Interfaz que muestra la ayuda en formato html

import wx, wx.html

_=wx.GetTranslation

class MyHelp1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyChild10.__init__
	# internacionalizacion
	wx.Locale_AddCatalogLookupPathPrefix("/etc/acept/watcherCat/lang")
	locale = wx.Locale(wx.LANGUAGE_DEFAULT)
	locale.AddCatalog("ayuda")
	self.idioma=locale.GetName()
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_6_staticbox = wx.StaticBox(self, -1, _("Contenidos"))
        self.sizer_5_staticbox = wx.StaticBox(self, -1, _("Indice"))
        self.list_box_1 = wx.ListBox(self, -1, choices=["",_("Como configurar un usuario"),_("Como definir o modificar un servicio"),_("Como definir o modificar una lista"), _("Como crear una lista local")])
        self.info=wx.html.HtmlWindow(self, -1,size=(200,200))
	#self.info.LoadPage('/root/inicio.html')
        self.button_1 = wx.Button(self, -1, _("Imprimir capitulo"))
	
        self.__set_properties()
        self.__do_layout()
        wx.EVT_LISTBOX(self,self.list_box_1.GetId(),self.linka)
	wx.EVT_BUTTON(self,self.button_1.GetId(),self.imprime)
	wx.EVT_CLOSE(self,self.cierra)
	# end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyChild10.__set_properties
        self.SetTitle(_("Ayuda"))
 	_icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/usr/share/acept/pixmaps/fondo_junta.gif", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyChild10.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_5.Add(self.list_box_1, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_6.Add(self.info, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_7.Add((20, 20), 1, 0, 0)
        sizer_7.Add(self.button_1, 1, 0, 0)
        sizer_7.Add((20, 20), 1, 0, 0)
        sizer_1.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_1.Add((20, 20), 0, 0, 0)
	self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade
    
    def cierra(self, event):
	padre=self.GetParent()
	padre.Show()
	self.Destroy()

    # Saca por la impresora una version para imprimir
    def imprime(self,event):
	path=self.info.GetOpenedPage()
	if len(path.split("html"))>1:
	    imp=Imprime()
	    imp.Print(path+"-print")

    # Abre una pagina u otra segun donde se pulse
    def linka(self,event):
	seleccion=self.list_box_1.GetSelections()[0]
	if seleccion==0:
	    path='/usr/share/acept/documentos/tutorial/'+self.idioma+'/blank.html'
	elif seleccion==1:
	    path='/usr/share/acept/documentos/tutorial/'+self.idioma+'/ini_conf_usr.html'
	elif seleccion==2:
	    path='/usr/share/acept/documentos/tutorial/'+self.idioma+'/av_conf_000.html'
	elif seleccion==3:
	    path='/usr/share/acept/documentos/tutorial/'+self.idioma+'/av_conf_000.html#crear'
	elif seleccion==4:
	    path='/usr/share/acept/documentos/tutorial/'+self.idioma+'/av_conf_000.html#liastas'
	
	from os.path import exists
	if exists(path.split('#')[0]):
	    self.info.LoadPage(path)

# Clase que se encarga de la impresion
class Imprime(wx.html.HtmlEasyPrinting):
    def __init__(self):
        wx.html.HtmlEasyPrinting.__init__(self)

    def Print(self, path):
        #self.SetHeader(doc_name)
        self.PrintFile(path)
