#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
#
# Fichero:	 barra.py
# Copyright: 	Junta de Andalucía <devmaster@guadalinex.org>
# Autor: 	Maria Dolores Perez Gutierrez y Nestor Chacon Manzano
# Fecha: 	lun nov 06 10:30:23 CET 2006
# Licencia: 	GPL v.2
#
# generated by wxGlade 0.4.1 on Fri Nov  3 10:26:51 2006
#
# Muestra barra de progreso mientras se actualizan la BD de blacklists

import wx
from os import getpid
from sys import argv
from time import sleep


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.FRAME_NO_TASKBAR|wx.NO_BORDER
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
	pdlg = wx.ProgressDialog(argv[1], "Este proceso puede consumir\n un tiempo considerable.                                                                                               " ,maximum=100, style = wx.PD_SMOOTH)
	_icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/usr/share/acept/pixmaps/fondo_junta.gif", wx.BITMAP_TYPE_ANY))
        pdlg.SetIcon(_icon)
	index=0
	try:
	    f=open("/tmp/milog2",'r')
	except:
	    mensaje="Este Proceso puede tardar un tiempo considerable."
	while True:
		sleep(0.05)
		if f:
		    mensaje=f.readline()
		pdlg.Update(index,mensaje)
		index=index+1
		if index >= 100 :
			index=0

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((1, 1))
        self.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class Inicio_App(wx.App):
        """ Inicializa el entorno GrÃ¡fico """
        def OnInit(self):
    	    wx.InitAllImageHandlers()
	    self.myframe=MyFrame(None,-1,"")
            self.myframe.Show()
            
            return True

pid=getpid()
f=open("/tmp/bklprg","w")
pid=str(pid)
f.write(pid)
f.close()
inicio=Inicio_App()
inicio.MainLoop()

